### ISSUE TITLE
getting RedGate Error "Encountered unknown SSMS version 12.0.0.0" opening SQL Server 2014 smss after insall beside SQL Server 2008R2

### ISSUE THREAD

**Issue by AAAEN** [red-gate/SIPFrameworkShared#4]
This is from RedGate folder logs

11:46:56.478|Error  |RedGate.SIPFramework|1  |#1:SIP Framework startup failed
System.ApplicationException: Encountered unknown SSMS version 12.0.0.0
   at RedGate.SharedSSMS.Util.VersionUtils.get_RunningSsmsVersion()
   at #akJ.#bkJ.get_VersionSpecificAssembly()
   at RedGate.SharedSSMS.VersionSpecificObjectFactory.Create[T]()
   at RedGate.SharedSSMS.Util.VersionSpecificClass`1.get_Implementation()
   at RedGate.SharedSSMS.ObjectExplorer.ObjectExplorer.HookUpEvents(DTE2 application)
   at RedGate.SIPFramework.Connect.OnStartupComplete(Array& custom)

**Comment by mauvo** [comment]
Right near the log file it should report which version of SIPFramework is running. It could be that this is an old version that needs updating. Or it could be that the install went wrong somehow. Either way first thing to try is reinstalling it. Remove SSMS Integration Pack Framework using Window's Programs and Features then I guess the easiest way to get the latest version is to install something like SQL Search - http://www.red-gate.com/products/sql-development/sql-search/
